name: Run E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install Chrome
        run: choco install googlechrome -y
  
      - name: Restore dependencies
        working-directory: ./SeleniumE2ECsharp  # Ajuste para seu caminho!
        run: dotnet restore

      - name: Install LivingDoc CLI    
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

      - name: Run tests
        working-directory: ./SeleniumE2ECsharp
        run: dotnet test --logger:"html;LogFileName=Result.html"