name: Run SpecFlow Tests with ChromeDriver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install ChromeDriver
        run: choco install chromedriver --version 135.0.7049.114
        env:
          ChocolateyInstall: C:\ProgramData\chocolatey

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests and generate HTML report
        run: dotnet test --logger:"html;LogFileName=TestResults/Result.html"

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: Result.html